// <auto-generated />
using CarListingApp.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarListingApp.Api.Migrations
{
    [DbContext(typeof(CarListDbContext))]
    partial class CarListDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("CarListingApp.Api.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Make = "Honda",
                            Model = "Fit",
                            Vin = "123"
                        },
                        new
                        {
                            Id = 2,
                            Make = "Toyota",
                            Model = "Prade",
                            Vin = "123"
                        },
                        new
                        {
                            Id = 3,
                            Make = "Honda",
                            Model = "Civic",
                            Vin = "123"
                        },
                        new
                        {
                            Id = 4,
                            Make = "Audi",
                            Model = "AS",
                            Vin = "123"
                        },
                        new
                        {
                            Id = 5,
                            Make = "BMw",
                            Model = "M1",
                            Vin = "123"
                        },
                        new
                        {
                            Id = 6,
                            Make = "Nissan",
                            Model = "Note",
                            Vin = "123"
                        },
                        new
                        {
                            Id = 7,
                            Make = "Ferrari",
                            Model = "Spider",
                            Vin = "123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
